### ISSUE TITLE
Can't build, can't find dependencies

### ISSUE THREAD

**Issue by ramn** [pjrt/stags#1]
Build fails since sbt assembly can't be found. 
`sbt.ResolveException: unresolved dependency: com.eed3si9n#sbt-assembly;0.14.4: not found`

Are you able to build with a fresy .ivy2 cache?

**Comment by pjrt** [comment]
@ramn I cleared my ivy and managed to get it:

```
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4 [info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.10/sbt_0.13/0.14.4/jars/sbt-assembly.jar ...
[info] 	[SUCCESSFUL ] com.eed3si9n#sbt-assembly;0.14.4!sbt-assembly.jar (1010ms)
```

Can you try again? It seems that the repo was down a couple of days ago: https://github.com/sbt/sbt-assembly/issues/239

**Comment by ramn** [comment]
Works now, thanks!

**Comment by pjrt** [comment]
I should get those other installation channels up...

**Comment by ramn** [comment]
`brew (cask) install stags` would be nice

**Comment by iamdotasb** [comment]
delete  .ivy2 can't help
