### ISSUE TITLE
support emacs tags

### ISSUE THREAD

**Issue by fommil** [pjrt/stags#14]
Generating ctags in emacs uses the `-e` flag it exuberant tags.

I don't know what that does, but it would be good if `stags` did that too!

**Comment by pjrt** [comment]
`-e` in ctags generates `etags` (which are different from the common ctags format used by vim). 

https://www.wikiwand.com/en/Ctags#/Etags_2

Will need to do some investigation on how different `etags` are from regular ctags.

**Comment by pjrt** [comment]
Ok, so Hasktags supports etags: https://github.com/MarcWeber/hasktags/blob/master/src/Tags.hs#L149-L160

This is the closest thing I've found to an actual explanation of what etags are. I can't seem to find any documentation that just states how etags are made (that wiki article helps but it isn't detailed enough). 

No idea why Emacs uses such weird characters as space separators.

**Comment by pjrt** [comment]
Oh, that's the length of the WHOLE line, not just the text definition. Ok, I think I get it now.
