### ISSUE TITLE
Any way to use stags as an sbt task

### ISSUE THREAD

**Issue by lewis6991** [pjrt/stags#6]
The README provides a way to get stags-cli using coursier, however would it be possible to use stags as an sbt plugin so tag generation can be automated after every compile?

**Comment by pjrt** [comment]
There isn't such a plugin right now. There are a couple of actual CTags plugins (iirc, one allows you to specify the cli to call). However they all had some issues. 

I've been thinking of making a plugin but haven't really had time.

**Comment by pjrt** [comment]
Btw, you can get the tags generation library (`stags`, without the `cli`) as a dependency of a project, in case you want to play around with it.

**Comment by lewis6991** [comment]
Any tips on how to do so? I had a go but couldn't figure it out. Googleing this stuff is hard as hell.

**Comment by pjrt** [comment]
Tips on making an sbt plugin? Not really sure, never really made one.

**Comment by lewis6991** [comment]
I mean getting stags as a dependency of another sbt project.

**Comment by pjrt** [comment]
Same way any other dependency: `libraryDependencies += "co.pjrt" % "stags_2.12" % "0.2.6"`
